AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: RAG demo API for dantenavarro.com (HTTP API -> Python Lambda)

Parameters:
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API key used for embeddings and response generation.
  AllowedOrigins:
    Type: CommaDelimitedList
    Description: CORS allowlist origins for browser requests.
  ChatModel:
    Type: String
    Default: gpt-4.1-nano
    Description: Chat model used for answer generation.
  EmbeddingModel:
    Type: String
    Default: text-embedding-3-small
    Description: Embedding model used for vector retrieval.

Resources:
  RagDemoApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: !Ref AllowedOrigins
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - content-type
      DefaultRouteSettings:
        ThrottlingBurstLimit: 8
        ThrottlingRateLimit: 4

  RagDemoFeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: feedbackId
          AttributeType: S
      KeySchema:
        - AttributeName: feedbackId
          KeyType: HASH

  RagDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handler.lambda_handler
      Runtime: python3.12
      Timeout: 20
      MemorySize: 1024
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          CHAT_MODEL: !Ref ChatModel
          EMBEDDING_MODEL: !Ref EmbeddingModel
          TOP_K: 6
          MAX_CONTEXT_CHUNKS: 6
          VECTOR_CANDIDATE_K: 12
          LEXICAL_CANDIDATE_K: 12
          MIN_SIMILARITY: 0.18
          CHUNK_SIZE: 500
          CHUNK_OVERLAP: 100
          RRF_K: 60
          POLICY_PDF_PATH: /var/task/data/nestle_hr_policy.pdf
          POLICY_TEXT_PATH: /var/task/data/nestle_hr_policy.txt
      Events:
        RagDemoPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagDemoApi
            Path: /rag-demo
            Method: POST

  RagDemoFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/feedback_handler.lambda_handler
      Runtime: python3.12
      Timeout: 10
      MemorySize: 512
      Environment:
        Variables:
          FEEDBACK_TABLE_NAME: !Ref RagDemoFeedbackTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: RagDemoFeedbackWrite
              Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt RagDemoFeedbackTable.Arn
      Events:
        RagDemoFeedbackPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagDemoApi
            Path: /rag-demo/feedback
            Method: POST

Outputs:
  RagDemoApiBaseUrl:
    Description: Base URL for the rag demo API.
    Value: !Sub https://${RagDemoApi}.execute-api.${AWS::Region}.amazonaws.com
  RagDemoApiUrl:
    Description: Rag demo endpoint URL.
    Value: !Sub https://${RagDemoApi}.execute-api.${AWS::Region}.amazonaws.com/rag-demo
  RagDemoFeedbackTableName:
    Description: DynamoDB table used for rag demo feedback.
    Value: !Ref RagDemoFeedbackTable
